version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew dependencies
      - run: ./gradlew build
      - run: ./gradlew publishToMavenLocal
  wildfly:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: jboss/wildfly:16.0.0.Final
        command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    steps:
      - checkout
      - ps aux
      - run: curl localhost:9990/console/index.html
workflows:
  version: 2
  all:
    jobs:
      - build
      - wildfly:
          requires:
            - build