version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew build

      - run: ./gradlew publishToMavenLocal
  wildfly:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: jboss/wildfly:16.0.0.Final
        command: /opt/jboss/wildfly/bin/standalone.sh -bmanagement 0.0.0.0
      - steps:
          - checkout
          - run: ps -a
workflows:
  version: 2
  all:
    jobs:
      - build
      - wildfly